version: '3.1'

services:
  feedback-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: FEEDBACK
  feedback-service:
    build:
      context: ../../
      dockerfile: CICD/docker/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - feedback-db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}