version: '3.1'

services:
  minio:
    image: minio/minio
    command: server /data
    ports:
    - 9000:9000
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  feedback-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: FEEDBACK
  feedback-service:
    build:
      context: ../../
      dockerfile: CICD/docker/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - fluentd
      - feedback-db
    links:
      - fluentd
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access